//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

mod utils;

pub mod prelude;

pub mod address;
pub mod baker;
pub mod bakery;
pub mod cake;
pub mod cake_baker;
pub mod casbin_rule;
pub mod customer;
pub mod customer_address;
pub mod product;
pub mod product_category;
pub mod product_description;
pub mod product_model;
pub mod product_model_product_description;
pub mod sales_order_detail;
pub mod sales_order_header;
pub mod user;

seaography::register_entity_modules!([
    address,
    baker,
    bakery,
    cake,
    cake_baker,
    casbin_rule, // TODO: delete from graphql
    customer,
    customer_address,
    product,
    product_category,
    product_description,
    product_model,
    product_model_product_description,
    sales_order_detail,
    sales_order_header,
    user, // TODO: delete from graphql
]);
