//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::address::Entity as Address;
pub use super::customer::Entity as Customer;
pub use super::customer_address::Entity as CustomerAddress;
pub use super::product::Entity as Product;
pub use super::product_category::Entity as ProductCategory;
pub use super::product_description::Entity as ProductDescription;
pub use super::product_model::Entity as ProductModel;
pub use super::product_model_product_description::Entity as ProductModelProductDescription;
pub use super::sales_order_detail::Entity as SalesOrderDetail;
pub use super::sales_order_header::Entity as SalesOrderHeader;
pub use super::user::Entity as User;
