//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "product_model")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub product_model_id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub catalog_description: Option<String>,
    #[sea_orm(unique)]
    pub rowguid: Uuid,
    #[serde(deserialize_with = "super::utils::date_time_from_str")]
    pub created_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::product::Entity")]
    Product,
    #[sea_orm(has_many = "super::product_model_product_description::Entity")]
    ProductModelProductDescription,
}

impl Related<super::product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Product.def()
    }
}

impl Related<super::product_model_product_description::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductModelProductDescription.def()
    }
}

impl Related<super::product_description::Entity> for Entity {
    fn to() -> RelationDef {
        super::product_model_product_description::Relation::ProductDescription.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::product_model_product_description::Relation::ProductModel
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::product::Entity")]
    Product,
    #[sea_orm(entity = "super::product_model_product_description::Entity")]
    ProductModelProductDescription,
    #[sea_orm(entity = "super::product_description::Entity")]
    ProductDescription,
}
