//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize)]
#[sea_orm(table_name = "product_model_product_description")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub product_model_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub product_description_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub culture: String,
    #[sea_orm(unique)]
    pub rowguid: Uuid,
    #[serde(deserialize_with = "super::utils::date_time_from_str")]
    pub created_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_description::Entity",
        from = "Column::ProductDescriptionId",
        to = "super::product_description::Column::ProductDescriptionId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductDescription,
    #[sea_orm(
        belongs_to = "super::product_model::Entity",
        from = "Column::ProductModelId",
        to = "super::product_model::Column::ProductModelId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ProductModel,
}

impl Related<super::product_description::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductDescription.def()
    }
}

impl Related<super::product_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductModel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::product_description::Entity")]
    ProductDescription,
    #[sea_orm(entity = "super::product_model::Entity")]
    ProductModel,
}
