//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize)]
#[sea_orm(table_name = "sales_order_detail")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub sales_order_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub sales_order_detail_id: i32,
    pub order_qty: i16,
    pub product_id: i32,
    pub unit_price: f64,
    pub unit_price_discount: f64,
    // pub line_total: Decimal,
    #[sea_orm(unique)]
    pub rowguid: Uuid,
    #[serde(deserialize_with = "super::utils::date_time_from_str")]
    pub created_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product::Entity",
        from = "Column::ProductId",
        to = "super::product::Column::ProductId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Product,
    #[sea_orm(
        belongs_to = "super::sales_order_header::Entity",
        from = "Column::SalesOrderId",
        to = "super::sales_order_header::Column::SalesOrderId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SalesOrderHeader,
}

impl Related<super::product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Product.def()
    }
}

impl Related<super::sales_order_header::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SalesOrderHeader.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::product::Entity")]
    Product,
    #[sea_orm(entity = "super::sales_order_header::Entity")]
    SalesOrderHeader,
}
